services:
  
  postgres:    
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: maindb
    ports:
      - 5432:5432
    volumes:
      - maindb-data:/var/lib/postgresql/data
        
volumes:
  maindb-data:
    driver: local